services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
      - "9010:9010"
    command: java ${JVM_PARAMS} ${JVM_VISUALVM_PARAMS_SERVER} com.github.kochkozharov.NioServer
  client:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9011:9011"
    depends_on:
      - server
    command: java ${JVM_PARAMS} ${JVM_VISUALVM_PARAMS_CLIENT} -XX:MaxDirectMemorySize=1G com.github.kochkozharov.NioClient
