services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    command: java ${JVM_PARAMS} com.github.kochkozharov.NioServer
  client:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - server
    ports:
      - "9010:9010"
    command: java ${JVM_PARAMS} ${JVM_VISUALVM_PARAMS} -XX:MaxDirectMemorySize=1G com.github.kochkozharov.NioClient
