services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
      - "9010:9010"
    command: ./submodules/hadroNIO/build/example/install/hadronio/bin/hadronio netty benchmark throughput --server --messages 1000 --length 1024
  client:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9011:9011"
    depends_on:
      - server
    command: ./submodules/hadroNIO/build/example/install/hadronio/bin/hadronio netty benchmark throughput --remote server --messages 1000 --length 1024
