services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
      - "9010:9010"
    command: java ${JVM_PARAMS} com.github.kochkozharov.Main server
  client:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9011:9011"
    depends_on:
      - server
    command: java ${JVM_PARAMS} com.github.kochkozharov.Main test_client
